apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nestjs
  template:
    metadata:
      labels:
        app: nestjs
    spec:
      containers:
      - name: nestjs
        image: hungtran36/nestjs
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
