apiVersion: v1
kind: Service
metadata:
  name: nginx-web-k8s
spec:
  type: LoadBalancer
  selector:
    app: nginx-web-k8s
  ports:
  - port: 3333
    targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-web-k8s
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-web-k8s
  template:
    metadata:
      labels:
        app: nginx-web-k8s
    spec:
      containers:
      - name: nginx-web-k8s
        image: hungtran36/nginx-web-k8s
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000